[package]
name = "tdiscord"
version = "0.1.0"
edition = "2024"


[dependencies]
serenity = { version = "0.12.4", default-features = false, features = ["client", "gateway", "rustls_backend", "model"] }
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
rusqlite = "0.37.0"
